# Generated by Django 5.2.13 on 2026-04-18 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_date', models.DateField(unique=True)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('prayer', models.TextField(blank=True, default='')),
                ('image_path', models.CharField(blank=True, default='', max_length=255)),
                ('readings_text', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'ordering': ['page_date'],
            },
        ),
        migrations.CreateModel(
            name='ReadingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('text', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_links', to='pages.dailypage')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
